// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sczgabjqkxxtqbfsqccn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjemdhYmpxa3h4dHFiZnNxY2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMTE1MzQsImV4cCI6MjA5MDY4NzUzNH0.WeuJMmVVJL8GTx0e1s52FgTFgWpQZcqK4nZxtNnXvyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});